### ISSUE TITLE
Guice configuration errors run proteus-example on ubuntu 16, oracle jdk 1.8

### ISSUE THREAD

**Issue by easykoala** [noboomu/proteus#15]
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:
1) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=security.callbackPath) was bound.
Did you mean?
* java.lang.String annotated with @com.google.inject.name.Named(value=user.country)
* java.lang.String annotated with @com.google.inject.name.Named(value=openapi.info.version)
* java.lang.String annotated with @com.google.inject.name.Named(value=application.fallbackHandler)
107 more bindings with other annotations.
while locating java.lang.String annotated with @com.google.inject.name.Named(value=security.callbackPath)
for field at io.sinistral.example.modules.SecurityModule.callbackPath(SecurityModule.java:46)
while locating io.sinistral.example.modules.SecurityModule
......
4 errors
at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1075)
at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1034)
at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
at io.sinistral.proteus.ProteusApplication.lambda$start$0(ProteusApplication.java:146)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at io.sinistral.proteus.ProteusApplication.start(ProteusApplication.java:146)
at io.sinistral.example.ExampleApplication.main(ExampleApplication.java:45)

**Comment by noboomu** [comment]
Can you please provide your configuration file?

**Comment by easykoala** [comment]
I have no any configuration file，it from https://github.com/noboomu/proteus-example

**Comment by noboomu** [comment]
Try creating a config file from the example and make sure security.callbackPath is specified.

**Comment by easykoala** [comment]
sorry，I've found the cause. after using maven package into a fat jar, I open the fat jar and see the application.conf has not been updated！Why? :)

**Comment by easykoala** [comment]
good luck!
