### ISSUE TITLE
Problem with @Path with regex and @PathParam

### ISSUE THREAD

**Issue by zloster** [noboomu/proteus#9]
I have a method:
```
@GET
@Path("{givenDate:[0-9]}")
public ServerResponse<Rates> givenDate(ServerRequest request, @PathParam("givenDate") String from) {
...
```
When I try to call the method, I get:
```
UT005071: Undertow request failed HttpServerExchange{ GET /v1/method/1 request {Accept=[application/json], Accept-Language=[en-US,en;q=0.5], Accept-Encoding=[gzip, deflate], DNT=[1], Origin=[http://localhost:8090], User-Agent=[Mozilla/5.0], Connection=[keep-alive], Referer=[http://localhost:8090/v1/openapi], Host=[localhost:8090]} response {Server=[proteus]}}
java.lang.IllegalArgumentException: Missing parameter givenDate
	at io.sinistral.proteus.server.Extractors.string(Extractors.java:397)
	at io.sinistral.proteus.controllers.handlers.CurrencyConvertRouteSupplier$2.handleRequest(CurrencyConvertRouteSupplier.java:56)
	at io.sinistral.example.wrappers.DummyWrapper$1.handleRequest(DummyWrapper.java:39)
	at io.undertow.server.handlers.accesslog.AccessLogHandler.handleRequest(AccessLogHandler.java:138)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.sinistral.proteus.server.handlers.ServerDefaultHttpHandler.handleRequest(ServerDefaultHttpHandler.java:70)
	at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68)
	at io.undertow.server.protocol.http2.Http2UpgradeHandler.handleRequest(Http2UpgradeHandler.java:102)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
Caused by: java.lang.NullPointerException: null
	at io.sinistral.proteus.server.Extractors.string(Extractors.java:394)
	... 20 common frames omitted
java.lang.IllegalArgumentException: Missing parameter givenDate
	at io.sinistral.proteus.server.Extractors.string(Extractors.java:397) ~[proteus-core-0.3.7-SNAPSHOT.jar:na]
	at io.sinistral.proteus.controllers.handlers.CurrencyConvertRouteSupplier$2.handleRequest(CurrencyConvertRouteSupplier.java:56) ~[na:na]
	at io.sinistral.example.wrappers.DummyWrapper$1.handleRequest(DummyWrapper.java:39) ~[classes/:na]
	at io.undertow.server.handlers.accesslog.AccessLogHandler.handleRequest(AccessLogHandler.java:138) ~[undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93) ~[undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at io.sinistral.proteus.server.handlers.ServerDefaultHttpHandler.handleRequest(ServerDefaultHttpHandler.java:70) ~[proteus-core-0.3.7-SNAPSHOT.jar:na]
	at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68) ~[undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at io.undertow.server.protocol.http2.Http2UpgradeHandler.handleRequest(Http2UpgradeHandler.java:102) ~[undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360) ~[undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255) ~[undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) ~[undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162) [undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100) [undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57) [undertow-core-2.0.15.Final.jar:2.0.15.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.3.8.Final.jar:3.3.8.Final]
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) [xnio-api-3.3.8.Final.jar:3.3.8.Final]
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) [xnio-api-3.3.8.Final.jar:3.3.8.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.3.8.Final.jar:3.3.8.Final]
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129) [xnio-nio-3.3.8.Final.jar:3.3.8.Final]
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582) [xnio-nio-3.3.8.Final.jar:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466) [xnio-nio-3.3.8.Final.jar:3.3.8.Final]
Caused by: java.lang.NullPointerException: null
	at io.sinistral.proteus.server.Extractors.string(Extractors.java:394) ~[proteus-core-0.3.7-SNAPSHOT.jar:na]
	... 20 common frames omitted
```

Please note that `io.sinistral.proteus.server.Extractors.string(Extractors.java:394)` is calling `HttpServerExchange.getQueryParameters()` and I suspect that the call should be `HttpServerExchange.getPathParameters()`.

**Comment by zloster** [comment]
Renaming the Java parameter doesn't help - the error is the same. The code is using the different names for "@PathParam" and the method parameter. But renaming them to be the same still gives error.
I've added simple tests here: https://github.com/zloster/proteus/commit/69e426ad4f380629ea273cfa30b78a747b1c873e

**Comment by noboomu** [comment]
If you remove the regex, and simply make the value of the path param “{givenDate}” does that work properly?
